### ISSUE TITLE
Doc update at www.beast2.org/managing-packages 

### ISSUE THREAD

**Issue by richelbilderbeek** [BEAST2-Dev/beast-docs#1]
As I know no better place to post, I will do so here:

The page http://www.beast2.org/managing-packages displays the previous way to call the package manager:

```
java -cp beast.jar beast.util.AddOnManager
```

It should be the new name:

```
java -cp beast.jar beast.util.PackageManager
```

I hope this Issue will reach the right people. Pinpointing me to where to post this Issue would also be fine!

**Comment by walterxie** [comment]
done
